[project]
name = "waymo-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "appium-python-client>=4.4.0",
    "python-dotenv>=1.0.1",
]
